### ISSUE TITLE
Refactor code base

### ISSUE THREAD

**Issue by silviu-toderita** [supermileage/UrbanSteeringFirmware#21]
Make this code more object-oriented and modular so that it's easy to change and upgrade over time.

**Comment by silviu-toderita** [comment]
@cosparks do you think there's more work to do on this other than just a big code refactor for the whole project?

**Comment by cosparks** [comment]
I think a big refactor and then maybe possibly adding or changing some graphics, but that could be under a separate issue?

**Comment by silviu-toderita** [comment]
@cosparks sounds good, I'll update this
