### ISSUE TITLE
Update PCB Repo

### ISSUE THREAD

**Issue by silviu-toderita** [supermileage/UrbanSteeringFirmware#35]
Update the PCB repo with the changes that we need to make, before we forget:

- Add 10k pull-down resistor between proxim input and GND
- Disconnect buttons shift register PL pin from GND and connect it to STCP (Latch) pin

**Comment by adityab82** [comment]
Update schematic and layout and commited to PCBv4 branch

**Comment by silviu-toderita** [comment]
Thanks, looks good! I accidentally made this issue in the Firmware project, I'll close it now.
